### ISSUE TITLE
Class 'Scrumpy\ProseMirrorToHtml\Marks\Mark' not found - if align text option used in bard

### ISSUE THREAD

**Issue by aadind** [OptimoApps/statamic-bard-text-align#1]
Installed plugin a few days back  & now I'm getting errors in multiple posts as follows: 
 Running composer update dint help. 
```
Error
Class 'Scrumpy\ProseMirrorToHtml\Marks\Mark' not found
http://sssuhev3/divine-guidance/sri-madiyal-narayan-bhat
```

if clear the formatting and DONT use the text align options in bard, page renders perfectly. 

my sample page content HTML source looks as follows: 
`<p><span style="text-align: justify; display: block">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Eget imperdiet quis eget tortor ut lacus mauris scelerisque. Sit.</span></p>
`

**Comment by ssatz** [comment]
This is due to recent change of namespace from tiptap. I will tag a new version today EOD. Thanks!

**Comment by ssatz** [comment]
Fixed! Please re-open if you encounter the same issue

**Comment by aadind** [comment]
Working perfectly! thanks for quick response!
