### ISSUE TITLE
Multiple links text align center

### ISSUE THREAD

**Issue by Hesesses** [OptimoApps/statamic-bard-text-align#11]
Hello and thank you creating for creating this plugin!

I created an issue to statamic related to stripped tags when centering texts.
Do you know if this is related to statamic or bard-text-align plugin?

https://github.com/statamic/cms/issues/4588

**Comment by ssatz** [comment]
It will add span tag. Please remove bard text align and check

**Comment by ssatz** [comment]
Statamic 3.4 Support #19
