### ISSUE TITLE
Can't disable text align options

### ISSUE THREAD

**Issue by axelferdinand** [OptimoApps/statamic-bard-text-align#14]
Even though text align options are disabled in the fieldset settings, they appear in the editor.

Fieldset settings:
<img width="662" alt="image" src="https://user-images.githubusercontent.com/10460870/156329238-46a138d6-f404-4d19-a7e3-c2e2971f60d7.png">

Result:
<img width="843" alt="image" src="https://user-images.githubusercontent.com/10460870/156329279-45ad2029-2945-415b-a88b-f1393e1e35ec.png">

**Comment by fitzage** [comment]
Same. And usually they seem to force themselves to the left, making it even worse.
