### ISSUE TITLE
Why is it adding display:block?

### ISSUE THREAD

**Issue by sebszocinski** [OptimoApps/statamic-bard-text-align#15]
I'm trying to add two links next to each other with text align centre and it's adding display:block to each one, can this be avoided or disabled via an option?

https://github.com/OptimoApps/statamic-bard-text-align/blob/83dad0ee013fcfc823e807617d89bc4b0aa63a98/resources/js/TextAlign.js#L32

**Comment by sebszocinski** [comment]
bump... ?

**Comment by globalexport** [comment]
Hi!

It seems to have been handled with in the master branch. 
https://github.com/OptimoApps/statamic-bard-text-align/commit/f7ebca292df3b516e0573b5755d5488327c31cd1

I tried the change and it worked (no block elements) but it broke the alignment altogether.

**Comment by ssatz** [comment]
Statamic 3.4 Support #19
