### ISSUE TITLE
The editor "forgets" the text align

### ISSUE THREAD

**Issue by axelferdinand** [OptimoApps/statamic-bard-text-align#16]
Sometimes this weird behavior happens: The editor "forgets" the text align.

To reproduce:
1. Align some text.
2. Save entry and leave the page.
3. Open the entry in the CP again, and do a change in another bard module.
4. Save the entry and leave the page.

Now the bard editor has "forgotten" the initial text align.

Very weird.

**Comment by axelferdinand** [comment]
I really love this addon, and use it on all my projects, but do you have a chance to look at this issue? :)

**Comment by axelferdinand** [comment]
Got you, thanks for replying!

**Comment by ssatz** [comment]
If you would like to fix it I will happily accept your pull request

**Comment by ssatz** [comment]
Statamic 3.4 Support #19
