### ISSUE TITLE
Statamic 3.4.0 Support

### ISSUE THREAD

**Issue by ottz0** [OptimoApps/statamic-bard-text-align#18]
I'm using `statamic-bard-text-align` however I can't upgrade to 3.4.0 due to this package being unsupported. Will you support statamic 3.4.0?

**Comment by ottz0** [comment]
> I came here for the same issue. Then I took a look at the [upgrade guide](https://statamic.dev/upgrade-guide/3-3-to-3-4#bard-addons-extensions-will-no-longer-work) of Statamic 3.4.0 and there it states the following:
> 
> _Bard's underlying editor, Tiptap, has been updated from v1 to v2 which required significant changes to Bard. This means that Bard addons will no longer work until they've been updated to support Statamic 3.4.
> 
> You should check if the Bard addons you have installed have been updated for 3.4, **or if they are even necessary anymore since the native Bard editor now has more features.**_
> 
> Looking at the [release notes of v3.4.0](https://github.com/statamic/cms/releases/tag/v3.4.0) it states that **text align support has now been added**.
> 
> After updating to Statamic 3.4.* and removing this plugin I checked the Bard field and see that additional options have becoming available. You can now enable or disable text align options from the cp.
> 
> ![image](https://user-images.githubusercontent.com/81617758/217203769-18528bac-fd00-441e-acc1-c070678eeb20.png)
> 
> So this plugin has been very helpful but seems not necessary anymore...

thanks. I had to remove like 2000 references in the .yaml file and uninstall the addon

```
-
            type: textAlign
            attrs:
              align: center
```

**Comment by ssatz** [comment]
I think i should now retire this addon. Since it already added into BARD
