### ISSUE TITLE
Class 'Scrumpy\ProseMirrorToHtml\Marks\Mark' not found

### ISSUE THREAD

**Issue by sarunaslite** [OptimoApps/statamic-bard-text-align#2]
Statamic : 3.0.14
Statamic Bard Text Align : 1.0.0

Error in frontend
vendor/optimoapps/statamic-bard-text-align/src/TextAlign.php:16

**Comment by ssatz** [comment]
Update to latest version 1.0.1. This has been fixed

**Comment by sarunaslite** [comment]
Working. Thank you for the plugin 👍🏼

**Comment by sebszocinski** [comment]
Hey, i'm getting this error as well... latest version of Statamic and according to the Updates panel this plugin is up to date as well at version 1.0.0?

![image](https://user-images.githubusercontent.com/5466694/98053572-bec68980-1e88-11eb-969b-8cc715421d55.png)

**Comment by sebszocinski** [comment]
Another screenshot of the Addon:

![image](https://user-images.githubusercontent.com/5466694/98054090-039ef000-1e8a-11eb-9894-0178fed3c94a.png)

**Comment by ssatz** [comment]
Run `composer update` and let me know.

**Comment by sebszocinski** [comment]
I tried that, it didn't update anything.

It actually installed an older version first (when installed via CP) then I had to manually click update to latest version which only updated it to 1.0.0

**Comment by ssatz** [comment]
Try the below steps

1. Remove composer json lock file
2. Update the bard text Align version to 1.0.1 in composer.json
3. Run composer install

If didn't work then I need to check with statamic.
It didn't updated to the latest version in addons page.

**Comment by sebszocinski** [comment]
ok, I deleted the addon via CP and then deleted composer.lock and manually tried installing from command line using `composer require optimoapps/statamic-bard-text-align` and this was the output:

```
composer require optimoapps/statamic-bard-text-align
Using version ^1.0 for optimoapps/statamic-bard-text-align
./composer.json has been updated
Running composer update optimoapps/statamic-bard-text-align
Loading composer repositories with package information
Updating dependencies
```

This time it installed the correct version (1.0.1) however! this is interesting... in the Statamic CP under Updates i'm seeing this:

![image](https://user-images.githubusercontent.com/5466694/98176240-0f50ec00-1f48-11eb-8eb7-a8896bf6a0d3.png)

![image](https://user-images.githubusercontent.com/5466694/98176065-c13be880-1f47-11eb-8db3-193f179b49f3.png)

It's showing I have version 1.0.1 installed but it's saying there are updates and asking if I want to update to the `Latest` being 1.0.0???

Also, on the Statamic Addon page it's showing version `1.0.0`:
https://statamic.com/addons/optimo-apps/statamic-bard-text-align
![image](https://user-images.githubusercontent.com/5466694/98176159-ef212d00-1f47-11eb-8e65-d6f0bbbc1467.png)

Note: I've had something similar happen with another addon where it wasn't using the latest version ([see here](https://github.com/octoper/statamic-inline-assets/issues/3)) so maybe it's something wrong on my end?
