### ISSUE TITLE
Versioning problem

### ISSUE THREAD

**Issue by sarunaslite** [OptimoApps/statamic-bard-text-align#5]
Statamic : 3.0.24
Statamic Bard Text Align :  V1.0.1

Statamic updater always shows that there are new update for the Bard text align plugin. 

<img width="956" alt="Screenshot 2020-11-05 at 09 49 48" src="https://user-images.githubusercontent.com/39726634/98212454-4923f180-1f4c-11eb-91c1-72f411c54274.png">

Problem is that we sometimes accidentally downgrading the plugin to version 1.0.0

Maybe the problem is with **V** letter in version number.

**Comment by ssatz** [comment]
I updated the release tag. Kindly let me know if still persist. I am open to any suggestions/practice  that it can be avoided in future.
