### ISSUE TITLE
Statamic detects previous versions as updates 

### ISSUE THREAD

**Issue by radovanobal** [OptimoApps/statamic-bard-text-align#6]
Currently statamic will display a update available for the package, but it will downgrade to 1.0.0 if update is run. 
![Screenshot from 2021-01-26 16-41-44](https://user-images.githubusercontent.com/60649057/105867449-67eacf00-5ff5-11eb-83ad-fe085bb15e00.png)

**Comment by ssatz** [comment]
Statamic 3.4 Support #19
